---
- hosts: localhost
  become: true
  vars:
    version: k8s1.0
    docker_name: nuttchai  
    images:
      - path: backend
        image_name: kk_api
      - path: Frontend
        image_name: kk_frontend
      - path: loginServer
        image_name: kk_loginserver
  
  tasks:
    - name: create docker image
      command: docker build -t {{ item.image_name }}:{{ version }} .
      args:
        chdir: /opt/docker/{{ item.path }}
      loop: "{{ images }}"

    - name: create tag to image
      command: docker tag {{ item.image_name }}:{{ version }} {{ docker_name }}/{{ item.image_name }}:{{ version }}
      loop: "{{ images }}"

    - name: push image on to dockerhub
      command: docker push {{ docker_name }}/{{ item.image_name }}:{{ version }}
      loop: "{{ images }}"
      
    - name: remove docker images from ansible server
      command: docker rmi {{ docker_name }}/{{ item.image_name }}:{{ version }} {{ item.image_name }}:{{ version }}
      loop: "{{ images }}"
      ignore_errors: yes
