---
- hosts: master
  become: true
  vars:
    old_version: k8s1.0
    new_version: k8s1.0
    docker_name: nuttchai
    service_name: webapp
    images: 
      - path: backend
        image_name: kk_api
      - path: Frontend
        image_name: kk_frontend
      - path: loginServer
        image_name: kk_loginserver

  tasks:
  - name: stop current service
    command: sudo docker stack rm {{ service_name }}
    ignore_errors: yes

  - name: remove current images
    command: sudo docker rmi {{ docker_name }}/{{ item.image_name }}:{{ old_version }}
    loop: "{{ images }}"
    ignore_errors: yes

  - name: pull new images
    command: sudo docker pull {{ docker_name }}/{{ item.image_name }}:{{ new_version }}
    loop: "{{ images }}"

  - name: start the service
    command: docker stack deploy -c docker-compose.yml {{ service_name }}
    args:
      chdir: /home/ubuntu/docker-swarm
