---
- hosts: docker
  become: true
  vars:
    old_version: build_test
    new_version: build_test
    docker_name: nuttchai

  tasks:
  - name: stop current running container
    command: docker stop api
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm api
    ignore_errors: yes

  - name: remove docker image
    command: docker rmi {{ docker_name }}/kk_api:{{ old_version }}
    ignore_errors: yes

  - name: pull docker image
    command: docker pull {{ docker_name }}/kk_api:{{ new_version }}

  # - name: building docker backend image
  #   command: docker build -t kk_api:{{ version }} .
  #   args:
  #     chdir: /opt/docker/backend

  - name: creating docker image using docker command
    command: docker run -d --name api -p 9000:9000 {{ docker_name }}/kk_api:{{ new_version }}
