export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADJUST_QTY = 'ADJUST_QTY';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';
export const LOAD_CURRENT_KIOSK = 'LOAD_CURRENT_KIOSK';

export const FETCH_KIOSKS_REQUEST = 'FETCH_KIOSKS_REQUEST';
export const FETCH_KIOSKS_SUCCESS = 'FETCH_KIOSKS_SUCCESS';
export const FETCH_KIOSKS_FAIL = 'FETCH_KIOSKS_FAIL';
