export const ADD_TO_CART = 'ADD_TO_CART';
export const REFRESH_CART = 'REFRESH_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADJUST_QTY = 'ADJUST_QTY';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';
export const LOAD_CURRENT_KIOSK = 'LOAD_CURRENT_KIOSK';
export const LOAD_ORDER_STATUS = 'LOAD_ORDER_STATUS';

export const LOAD_CURRENT_ORDER = 'LOAD_CURRENT_ORDER';


export const FETCH_KIOSKS_REQUEST = 'FETCH_KIOSKS_REQUEST';
export const FETCH_KIOSKS_SUCCESS = 'FETCH_KIOSKS_SUCCESS';
export const FETCH_KIOSKS_FAIL = 'FETCH_KIOSKS_FAIL';

export const FETCH_MYSTORE_REQUEST = 'FETCH_MYSTORE_REQUEST';
export const FETCH_MYSTORE_SUCCESS = 'FETCH_MYSTORE_SUCCESS';
export const FETCH_MYSTORE_FAIL = 'FETCH_MYSTORE_FAIL';
